[package]
name = "rustysilver"
version = "0.1.0"
authors = ["Bram Grooteman <bramgrooteman@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.6"
regex = "1"
lazy_static = "1.4.0"